#!/bin/bash
# This file is part of the Docker Image for a Docker:Git-Pull.
# Copyright (C) 2017 Martin Scharm <https://binfalse.de/contact/>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR=/git-project
LOG=/tmp/_git-pull.log-$(date "+%s")

PRE_PULL=/pre-pull
POST_PULL=/post-pull


cd $DIR
echo "> fetching..." > $LOG
git fetch >> $LOG 2>&1

echo "" >> $LOG
echo "> fetched ... checking for updated" >> $LOG
echo "" >> $LOG
git status | grep behind >> $LOG
stat=$?

echo "" >> $LOG
echo "> updates: $stat" >> $LOG

if [ $stat -eq 0 ] || [ "$1" = "-f" ]
then
        echo "> need to pull..." >> $LOG
        echo "" >> $LOG

        if [ -x "$PRE_PULL" ]
        then
            echo "> running pre-pull script" >> $LOG
            $PRE_PULL >> $LOG 2>&1
        fi

        echo "> pulling..." >> $LOG
        echo "" >> $LOG
        git pull >> $LOG 2>&1
        echo "" >> $LOG
        echo "> pulled..." >> $LOG
        echo "" >> $LOG

        if [ -x "$POST_PULL" ]
        then
            echo "> running post-pull script" >> $LOG
            $POST_PULL >> $LOG 2>&1
        fi

        echo "" >> $LOG
        echo "> everything's done. printing log for mail or something..." >> $LOG
        echo "" >> $LOG

        echo "done" >> $LOG

        cat $LOG
        rm $LOG
else
        rm $LOG
fi



