#!/bin/bash
# This file is part of the Docker Image for Jekyll+Git.
# Copyright (C) 2017 Martin Scharm <https://binfalse.de/contact/>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR=/jekyll
LOG=$DIR/_jekyll_build.log-$(date "+%s")


cd $DIR
echo "> fetching..." > $LOG
git fetch >> $LOG 2>&1

echo "" >> $LOG
echo "> fetched ... checking for updated" >> $LOG
echo "" >> $LOG
git status | grep behind >> $LOG
stat=$?

echo "" >> $LOG
echo "> updates: $stat" >> $LOG

if [ $stat -eq 0 ] || [ "$1" = "-f" ]
then
        echo "> need to pull..." >> $LOG
        echo "" >> $LOG
        git pull > /dev/null
        echo "" >> $LOG
        echo "> pulled ... now rebuilding site" >> $LOG
        echo "" >> $LOG

        /usr/local/bin/jekyll build >> $LOG
        echo "" >> $LOG
        echo "> everythings done. writing mail..." >> $LOG
        echo "" >> $LOG

        echo "go to https://binfalse.de" >> $LOG

        cat $LOG
else
        rm $LOG
fi



